name: SmartUI SDK Cloud GitHub Actions
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      username:
        required: true
        description: LT Username
      accessKey:
        required: true
        description: LT Access Key
      projectToken:
        required: true
        description: PROJECT Token

jobs:
  smartui-sdk-cloud-github-actions:
    name: SmartUI SDK Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Dependencies and clean directory
        run: |
          npm i @lambdatest/smartui-cli

      - name: Export your Credentials
        run: |
          export LT_USERNAME=${{ github.event.inputs.username }}
          export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
          export PROJECT_TOKEN=${{ github.event.inputs.projectToken }}
          
      - name: Execute your tests
        run: |
          npx smartui --version
          npx smartui config:create smartui-web.json
          npx smartui --config smartui-web.json exec -- mvn --quiet test -D suite=sdk-cloud.xml
